name: update tianheg profile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stale:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - name: Install dependecies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d # Install all dependencies, including development ones
      - name: Build
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run build
      - name: Commit and push if changed   # 更新README.md
        run: |
          git diff
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "bot: update README.md automatically"
          git push
    # - name: Install dependecies
    #   uses: tianheg/github-actions@pipenv
    #   with:
    #     command: install --dev # Install all dependencies, including development ones
    # - name: Build
    #   uses: tianheg/github-actions@pipenv
    #   with:
    #     command: run build
    # - name: Commit and push if changed   # 更新README.md
    #   run: |
    #       git diff
    #       git config --global user.email "52186032+tianheg@users.noreply.github.com"
    #       git config --global user.name "tianheg"
    #       git add README.md
    #       git commit -m "Github Action Auto Updated"
    #       git push